### PR TITLE
Clarify Linux host support and fail before daemon/setup side effects

### PR DESCRIPTION
**Pull request by hqhq1025**
## Summary

Addresses the near-term documentation / actionable-failure option explicitly requested in #9. This does not implement a Linux clipboard-host backend.

- Publish an explicit macOS / Windows / native Linux / WSL2 host-versus-consumer matrix in the README, agent instructions, and LLM-facing docs.
- Reject daemon startup on unsupported hosts before starting the HTTP server; reject host-side ssh-setup before checking or changing anything.
- Explain that Linux compilation provides diagnostic and consumer setup commands, not a Wayland/X11 clipboard watcher. Keep those commands buildable and usable.
- Add the doctor role `unsupported-host` with a single failing platform check and `fix: null`, while preserving WSL precedence, actual SSH sessions, and configured Linux consumers without SSH variables.
- Add isolated Linux process-level tests for CLI errors, role classification, mocked bridge success/failure, and successful WSL helper installation. Add Linux/macOS/Windows CI.

## Validation

- Reproduced the native-Linux-as-SSH-remote misclassification in a failing regression test before changing the decision logic.
- macOS: 67 unit tests passed; strict Clippy passed.
- Windows MSVC cross-target strict Clippy passed.
- Linux cross-target Clippy passed with existing unused image/cache warnings; actual Linux execution is covered by the new CI job.
- Tests use temporary homes and fake curl responses; they do not contact a daemon, modify the real home directory, or touch the general clipboard.

## Scope and compatibility

This extends the doctor JSON role enum; consumers should accept `unsupported-host`. Native Linux hosting remains unsupported and would need a separately designed Wayland/X11 backend. Keeping #9 linked rather than auto-closing it allows that feature discussion to remain explicit. No release tag or published artifact is changed.

### CODE REVIEW

**Comment by hqhq1025** [comment]
Validation completed for head 0a0224e58d9b47ce8335d6cc786734668d0581ec:

- Linux: 52 unit tests and all 7 isolated CLI tests passed.
- macOS: 67 tests passed.
- Windows: 48 tests passed.
- Clippy passed on all three CI runners. Linux retains pre-existing unused image/cache warnings; strict local macOS and cross-target Windows checks passed.

CI: https://github.com/hqhq1025/clipaste/actions/runs/34570818192

The runtime checks include a successful WSL helper installation and both successful and failed configured-consumer bridge probes using a temporary home and fake curl. No live clipboard or external server is used. This PR addresses the docs/diagnostic option in #9, not native Linux clipboard hosting.
